name: pico_clock
description: A voice-controlled clock app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.9
  picovoice_flutter: ^2.1.0
  flutter_ringtone_player: ^3.0.0  
  fluttertoast: ^8.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
      - assets/android/pico clock_android.ppn
      - assets/android/clock_android.rhn
      - assets/ios/pico clock_ios.ppn
      - assets/ios/clock_ios.rhn
