[package]
name = "picovoice"
version = "2.1.0"
edition = "2018"
description = "Rust SDK for Picovoice's voice recognition platform"
license = "Apache-2.0"
homepage = "https://picovoice.ai/"
repository = "https://github.com/Picovoice/picovoice"
keywords = [
    "natural-language",
    "speech-recognition",
    "voice-control",
    "voice-recognition",
    "wake-word",
]
publish = true

exclude = [
    "tests/",
]

[lib]
name = "picovoice"
path = "src/lib.rs"
crate_type = ["lib"]

[dependencies]
pv_porcupine = "2.1.0"
pv_rhino = "2.1.0"
