name: picovoice_demo
description: Demonstrates how to use the picovoice plugin.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.0.9
  picovoice_flutter: 
    path: ../../sdk/flutter

flutter:
  assets:
    - assets/contexts/android/smart_lighting_android.rhn
    - assets/contexts/ios/smart_lighting_ios.rhn
    - assets/keyword_files/android/picovoice_android.ppn
    - assets/keyword_files/ios/picovoice_ios.ppn
  uses-material-design: true
dev_dependencies: 
  lints: ^1.0.1
