name: picovoice_demo
description: Demonstrates how to use the picovoice plugin.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  picovoice_flutter: ^3.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/contexts/android/
    - assets/contexts/ios/
    - assets/keywords/android/
    - assets/keywords/ios/
    - assets/models/
    - assets/test_resources/
    - assets/test_resources/audio_samples/
    - assets/test_resources/context_files/
    - assets/test_resources/keyword_files/
    - assets/test_resources/model_files/
