name: Angular Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/angular/*.js'
      - '**/angular/*.ts'
      - '.github/workflows/angular-codestyle.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**/angular/*.js'
      - '**/angular/*.ts'
      - '.github/workflows/angular-codestyle.yml'

jobs:
  check-angular-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn
      
    - name: Build Local Porcupine Web SDK
      run: yarn && yarn copywasm && yarn copyppn && yarn build
      working-directory: resources/porcupine/binding/web
      
    - name: Build Local Rhino Web SDK
      run: yarn && yarn copywasm && yarn build
      working-directory: resources/rhino/binding/web
      
    - name: Build Local SDK
      run: yarn && yarn build
      working-directory: sdk/web

    - name: Build Local Angular SDK
      run: yarn && yarn build
      working-directory: sdk/angular

    - name: Run SDK Linter
      run: yarn && yarn lint
      working-directory: sdk/angular

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/angular
