name: .NET Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demos.yml'

defaults:
  run:
    working-directory: demo/dotnet/PicovoiceDemo

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
          nuget-path: ~/.nuget/NuGet/local-nuget
        - os: windows-latest
          platform: windows
          nuget-path: ~/AppData/Roaming/NuGet/local-nuget
        - os: macos-latest
          platform: mac
          nuget-path: ~/.nuget/NuGet/local-nuget

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # *********** REMOVE AFTER RELEASE **********************
    - name: mkdir NuGet directory
      run: mkdir -p ${{ matrix.nuget-path }}

    - name: Add local NuGet source
      run: dotnet nuget add source local-nuget

    - name: Pack Porcupine for local ref
      run: dotnet pack -c Release
      working-directory: resources/porcupine/binding/dotnet

    - name: Copy Porcupine Nuget
      run: cp ../../../resources/porcupine/binding/dotnet/Porcupine/bin/Release/*.nupkg ${{ matrix.nuget-path }}

    - name: Pack Rhino for local ref
      run: dotnet pack -c Release
      working-directory: resources/rhino/binding/dotnet

    - name: Copy Rhino Nuget
      run: cp ../../../resources/rhino/binding/dotnet/Rhino/bin/Release/*.nupkg ${{ matrix.nuget-path }}

    - name: Pack Picovoice for local ref
      run: dotnet pack ../../../sdk/dotnet/Picovoice/Picovoice.csproj -c Release

    - name: Copy Picovoice Nuget
      run: cp ../../../sdk/dotnet/Picovoice/bin/Release/*.nupkg ${{ matrix.nuget-path }}
    # ******************************************************

    - name: Dotnet build micdemo
      run: dotnet build -c MicDemo.Release -v n

    - name: Dotnet build filedemo
      run: dotnet build -c FileDemo.Release -v n

    - name: Run Dotnet filedemo
      run: dotnet run -c FileDemo.Release --
        --input_audio_path ../../../resources/audio_samples/picovoice-coffee.wav
        --access_key ${{secrets.PV_VALID_ACCESS_KEY}}
        --keyword_path ../../../resources/porcupine/resources/keyword_files/${{ matrix.platform }}/picovoice_${{ matrix.platform }}.ppn
        --context_path ../../../resources/rhino/resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
        - machine: rpi2
          platform: raspberry-pi
        - machine: rpi3-32
          platform: raspberry-pi
        - machine: rpi3-64
          platform: raspberry-pi
        - machine: rpi4-32
          platform: raspberry-pi
        - machine: rpi4-64
          platform: raspberry-pi
        - machine: jetson
          platform: jetson
        - machine: beaglebone
          platform: beaglebone

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # *********** REMOVE AFTER RELEASE **********************
    - name: Pack Porcupine for local ref
      run: dotnet pack -c Release
      working-directory: resources/porcupine/binding/dotnet

    - name: Copy Porcupine Nuget
      run: cp ../../../resources/porcupine/binding/dotnet/Porcupine/bin/Release/*.nupkg ~/.nuget/NuGet/local-nuget

    - name: Pack Rhino for local ref
      run: dotnet pack -c Release
      working-directory: resources/rhino/binding/dotnet

    - name: Copy Rhino Nuget
      run: cp ../../../resources/rhino/binding/dotnet/Rhino/bin/Release/*.nupkg ~/.nuget/NuGet/local-nuget

    - name: Pack Picovoice for local ref
      run: dotnet pack ../../../sdk/dotnet/Picovoice/Picovoice.csproj -c Release

    - name: Copy Picovoice Nuget
      run: cp ../../../sdk/dotnet/Picovoice/bin/Release/*.nupkg ~/.nuget/NuGet/local-nuget
    # ******************************************************

    - name: Dotnet build micdemo
      run: dotnet build -c MicDemo.Release -v n

    - name: Dotnet build filedemo
      run: dotnet build -c FileDemo.Release -v n

    - name: Run Dotnet filedemo
      run: dotnet run -c FileDemo.Release --
        --input_audio_path ../../../resources/audio_samples/picovoice-coffee.wav
        --access_key ${{secrets.PV_VALID_ACCESS_KEY}}
        --keyword_path ../../../resources/porcupine/resources/keyword_files/${{ matrix.platform }}/picovoice_${{ matrix.platform }}.ppn
        --context_path ../../../resources/rhino/resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn